# 您的项目名称
name = "my-rembg-worker"

# 兼容性日期
compatibility_date = "2023-11-21"

# 告诉Pages，静态文件构建后放在 "public" 目录
pages_build_output_dir = "public"

# R2 存储桶绑定 (保留，以备后用)
[[r2_buckets]]
binding = "MY_MODEL_BUCKET"
bucket_name = "model-assets"

# 【新增】Workers AI 绑定
# 这会让您的代码可以通过 env.AI 来调用AI模型
[ai]
binding = "AI"