# 你的Worker项目的名字，可以随便起，比如 "my-model-worker"
name = "my-model-worker"

# 你的主代码文件。Cloudflare Pages + Workers模式下，通常是这个。
# 如果你没有这个文件，请创建一个。
main = "_worker.js"

# 兼容性设置，建议加上
compatibility_date = "2023-10-30"

# 你的R2绑定信息（这部分你写的是对的）
[[r2_buckets]]
binding = 'MY_MODEL_BUCKET'
bucket_name = 'model-assets'