# 你的Worker项目的名字
name = "my-rembg-worker"

# 兼容性设置
compatibility_date = "2023-11-21"

# 【关键】告诉Pages，静态文件构建后放在哪个目录
pages_build_output_dir = "public"

# 你的R2绑定信息
[[r2_buckets]]
binding = 'MY_MODEL_BUCKET'
bucket_name = 'model-assets'